[package]
name = "s3-sync-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = { version = "0.1.12", features = ["fs"] }
aws-sdk-s3 = "0.26.0"
aws-config = "0.55.1"
aws-smithy-types = "0.55.1"
aws-smithy-http = { version = "0.55.1", features = ["rt-tokio"] }
